services:
  - type: web
    name: ABGCalculator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server -b 0.0.0.0:10000"
    envVars:
      - key: PORT
        value: 10000
